### ISSUE TITLE
FileUploadExample does not finish

### ISSUE THREAD

**Issue by arsentiikaptsan** [activej/activej#91] opened 2021-06-02 21:41 UTC
File upload in FileUploadExample does not finish properly, I don't get "File 'example.txt' successfully uploaded" as expected, it just keeps waiting forever.  However I can see in the GUI that 'example.txt' is there with "example text" in it.

Tested on: 9f08c20efe309f13d248b81cba48d191f27f9e45 (revision number)

**Comment by eduard-vasinskyi** [comment] 2021-06-03 06:48
Hello, @arsentiikaptsan 
I could not reproduce that behavior locally. 
What OS / JDK version did you use? 
Did you run [ServerSetupExample](https://github.com/activej/activej/blob/master/examples/cloud/fs/src/main/java/ServerSetupExample.java) before running [FileUploadExample](https://github.com/activej/activej/blob/master/examples/cloud/fs/src/main/java/FileUploadExample.java)? Where there any exception logging output in ServerSetupExample?

**Comment by arsentiikaptsan** [comment] 2021-06-03 07:56
Sorry, I should have specified them right away:
**OS:** 

> MasOS 11.4

**JDK:** 

> openjdk version "11.0.10" 2021-01-19
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

Yes, I launch ServerSetupExample before FileUploadExample. There are no ERROR or WARN logs both on server and client.
Client logs:
`10:46:01.836 [FileUploadExample.main()] INFO FileUploadExample - === INJECTING DEPENDENCIES
10:46:01.930 [FileUploadExample.main()] INFO FileUploadExample.0 - Effective Injector:

digraph {
        rankdir=BT;
        "()->io.activej.launcher.Launcher" [label="Launcher"];
        "()->interface io.activej.launcher.annotation.OnStart java.util.concurrent.CompletionStage<java.lang.Void>" [label="@OnStart CompletionStage<Void>"];
        "()->interface io.activej.launcher.annotation.Args java.lang.String[]" [label="@Args String[]"];
        "()->io.activej.fs.tcp.RemoteActiveFs" [label="RemoteActiveFs"];
        "()->io.activej.inject.Injector" [label="Injector" style=bold];
        "()->FileUploadExample" [label="FileUploadExample"];
        "()->java.util.Set<io.activej.launcher.LauncherService>" [label="Set<LauncherService>"];
        "()->interface io.activej.launcher.annotation.OnComplete java.util.concurrent.CompletionStage<java.lang.Void>" [label="@OnComplete CompletionStage<Void>"];
        "()->interface io.activej.launcher.annotation.OnRun java.util.concurrent.CompletionStage<java.lang.Void>" [label="@OnRun CompletionStage<Void>"];
        "()->io.activej.inject.InstanceInjector<FileUploadExample>" [label="InstanceInjector<FileUploadExample>"];
        "()->@57ec5f56 io.activej.launcher.LauncherService" [label="@57ec5f56 LauncherService"];
        "()->java.util.Set<io.activej.inject.InstanceInjector<?>>" [label="Set<InstanceInjector<?>>"];
        "()->io.activej.eventloop.Eventloop" [label="Eventloop"];
        "()->io.activej.service.ServiceGraph" [label="ServiceGraph"];

        { rank=same; "()->io.activej.inject.Injector" "()->FileUploadExample" "()->interface io.activej.launcher.annotation.OnComplete java.util.concurrent.CompletionStage<java.lang.Void>" "()->interface io.activej.launcher.annotation.OnRun java.util.concurrent.CompletionStage<java.lang.Void>" "()->interface io.activej.launcher.annotation.OnStart java.util.concurrent.CompletionStage<java.lang.Void>" "()->io.activej.eventloop.Eventloop" "()->interface io.activej.launcher.annotation.Args java.lang.String[]" }

        "()->io.activej.launcher.Launcher" -> "()->FileUploadExample" [];
        "()->io.activej.fs.tcp.RemoteActiveFs" -> "()->io.activej.eventloop.Eventloop" [];
        "()->java.util.Set<io.activej.launcher.LauncherService>" -> "()->@57ec5f56 io.activej.launcher.LauncherService" [];
        "()->io.activej.inject.InstanceInjector<FileUploadExample>" -> "()->io.activej.eventloop.Eventloop" [];
        "()->io.activej.inject.InstanceInjector<FileUploadExample>" -> "()->io.activej.fs.tcp.RemoteActiveFs" [];
        "()->@57ec5f56 io.activej.launcher.LauncherService" -> "()->io.activej.inject.Injector" [];
        "()->java.util.Set<io.activej.common.api.Initializer<io.activej.service.ServiceGraphModuleSettings>>" [label="Set<Initializer<ServiceGraphModuleSettings>>" style=dashed, color=orange];
        "()->@57ec5f56 io.activej.launcher.LauncherService" -> "()->java.util.Set<io.activej.common.api.Initializer<io.activej.service.ServiceGraphModuleSettings>>" [style=dashed,];
        "()->@57ec5f56 io.activej.launcher.LauncherService" -> "()->io.activej.service.ServiceGraph" [];
        "()->java.util.Set<io.activej.inject.InstanceInjector<?>>" -> "()->io.activej.inject.InstanceInjector<FileUploadExample>" [];
        "()->io.activej.service.ServiceGraph" -> "()->io.activej.inject.Injector" [];
}

10:46:01.937 [FileUploadExample.main()] INFO FileUploadExample.0 - Created eager singletons
10:46:02.003 [FileUploadExample.main()] INFO FileUploadExample.0 - Post-injected instances: [FileUploadExample]
10:46:02.003 [FileUploadExample.main()] INFO FileUploadExample - === STARTING APPLICATION
10:46:02.003 [FileUploadExample.main()] INFO FileUploadExample.0 - Starting Root Services: [io.activej.service.ServiceGraphModule$1@1f044658]
10:46:02.004 [FileUploadExample.main()] INFO FileUploadExample.0 - Starting Root Service: io.activej.service.ServiceGraphModule$1@1f044658
10:46:02.008 [FileUploadExample.main()] INFO io.activej.service.ServiceGraph - Starting services
10:46:02.017 [FileUploadExample.main()] INFO io.activej.service.ServiceGraph - Started io.activej.eventloop.Eventloop in 5,146 ms
10:46:02.263 [eventloop: pool-2-thread-1] INFO io.activej.fs.tcp.RemoteActiveFs - ping ClusterActiveFs{address=0.0.0.0/0.0.0.0:6732} → null
10:46:02.264 [eventloop: pool-2-thread-1] INFO io.activej.service.ServiceGraph - Started io.activej.fs.tcp.RemoteActiveFs in 246,2 ms
10:46:02.267 [eventloop: pool-2-thread-1] INFO io.activej.service.ServiceGraphModule - Effective ServiceGraph:

digraph {
        rankdir=LR
        "io.activej.fs.tcp.RemoteActiveFs" -> "io.activej.eventloop.Eventloop" [color=blue style=bold]

        "io.activej.eventloop.Eventloop" [ label="Eventloop\n5 millis" color=blue style=bold ]
        "io.activej.fs.tcp.RemoteActiveFs" [ label="RemoteActiveFs\n247 millis" color=blue style=bold ]

        { rank=same; "io.activej.eventloop.Eventloop" }
}

10:46:02.274 [FileUploadExample.main()] INFO FileUploadExample - === RUNNING APPLICATION
10:46:03.322 [eventloop: pool-2-thread-1] INFO io.activej.fs.tcp.RemoteActiveFs - upload example.txt, 12, ClusterActiveFs{address=0.0.0.0/0.0.0.0:6732} → io.activej.csp.ChannelConsumer$12@4a63cbb1`

**Comment by eduard-vasinskyi** [comment] 2021-06-04 16:55
Thank you, @arsentiikaptsan

We could not reproduce the scenario on MacOS.
If you still have this issue, could you help us with debugging?
You can start with logging debug messages at the start/finish of file upload. Or you may set breakpoints in the debugger to see when the upload process hangs.

**Comment by arsentiikaptsan** [comment] 2021-06-09 22:21
Thanks for the swift response, @eduard-vasinskyi !

I created a separate [project](https://github.com/arsentiikaptsan/activej-fs-upload) for testing to be sure that my problem is not due to a bad maven configuration. I also added some logging on the client. I ran this example on different Mac OS versions and different machines, I also tested on linux and both on linux and Mac, where the client was running on Mac and the server on linux and vice versa. To be sure, that nothing is interfering with the test (like vpn clients, docker or antivirus), I rented clean VMs in the cloud. I used AdoptOpenJDK-11.0.11+9 in all tests on all platforms (however I also tried 1.8.0_252 with similar results).
To my surprise, I got nondeterministic results and didn't see any correlation with OS which client and server were running on. Sometimes FileUploadExample finished like it supposed to, sometimes it crashed with TruncatedDataException and sometimes uploading stalls while waiting for an acknowledgment from the server (debugging lead me to io.activej.fs.tcp.RemoteActiveFs.java:155). Maybe, after couple runs you would be able to reproduce this behavior on your machine.
I attached client and server TRACE logs + tcp dump for the run when client halts. If I can help with smth else, please let me know, I would be happy to do that.
[logs.zip](https://github.com/activej/activej/files/6627175/logs.zip)

Best regards,
Arsentii.

**Comment by arsentiikaptsan** [comment] 2021-06-09 22:24
Here is a client log with TruncatedDataException
[client.log](https://github.com/activej/activej/files/6627188/client.log)

**Comment by eduard-vasinskyi** [comment] 2021-06-14 17:05
@arsentiikaptsan 
Thank you for the impressive work on debugging the issue! Now it is clearer what we should look for. Unfortunately, I still could not reproduce the issue on local machines. Even when running the client in a loop, there were no halts or exceptions. We are setting up the remote server to test the issue right now. I will let you know once we finish testing. 

By the way, did you manage to reproduce the issue with both client and server being Linux machines? Could you please provide a TCP dump of a server (packets coming from port 6732 to a client)? Based on logs, it seems like the server has finished upload successfully, so it must have sent a `UploadFinished` acknowledgment, but the client did not receive it for some reason (it is not present in TCP dump).

**Comment by eduard-vasinskyi** [comment] 2021-06-17 15:10
Hello, @arsentiikaptsan
Unfortunately, we still cannot reproduce the hanging FS client nor TruncatedDataException with our current setup (2 Linux machines running JDK 11.0.11).
By the way, did you manage to get this issue while running both server and client on the same machine? 
 
I have created a separate branch [fs-upload-trace](https://github.com/activej/activej/tree/fs-upload-trace) with excessive traces that could help debug the issue. Could you, please, run your test project using this build and provide log output from the client and server? If you could also provide client/server TCP dumps when the client hangs or TruncatedDataException occurs, I would be grateful.

**Comment by arsentiikaptsan** [comment] 2021-06-21 20:30
Hi, @eduard-vasinskyi!
Sorry for the late reply, I've missed a notification. Yes, I was able to reproduce this behavior when client and server both were running linux (ubuntu 20.04). I ran your version with detailed logging, here what I've got on my Mac (where it always halts).
[logs+dump.zip](https://github.com/activej/activej/files/6689334/logs%2Bdump.zip)

**Comment by eduard-vasinskyi** [comment] 2021-06-23 07:01
@arsentiikaptsan
Thank you for the logs and a TCP dump. The `UploadFinished` message is sent by the server, but it is not received on the client side due to some possible networking problem (see below). I have added another commit to the [fs-upload-trace](https://github.com/activej/activej/tree/fs-upload-trace) branch that logs keys selected by the selector so that we can be sure that the `READ` operation is registered for the client’s socket channel. To help us troubleshoot your networking configuration please run the example once more on the latest commit in the branch.
 
[ActiveFsServer](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/tcp/ActiveFsServer.java) and [RemoteActiveFs](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/tcp/RemoteActiveFs.java) transport protocol is highly optimized, but requires network infrastructure to be fully compatible with TCP standards. Apparently, some routers / TCP implementations and their settings [may not follow TCP specs completely](https://www.excentis.com/blog/tcp-half-close-cool-feature-now-broken).
`upload()` in `RemoteActiveFs` uses TCP half-close, it is possible that some intermediate treats half-closed TCP connection as closed, which leads to hang-ups / `TruncatedDataException`
 
For full compatibility at the expense of minimal overhead, the HTTP implementation of the ActiveFs protocol can be used (that is [HttpActiveFs](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/http/HttpActiveFs.java) and [ActiveFsServlet](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/http/ActiveFsServlet.java)). Because the [ActiveJ HTTP](https://github.com/activej/activej/tree/master/core-http) module is highly optimized as well, you can expect the performance to be similar to the TCP setup.

**Comment by arsentiikaptsan** [comment] 2021-06-24 09:29
@eduard-vasinskyi thank you for detailed response! I ran a new version on Mac, here what I've got.
[logs_and_dump.zip](https://github.com/activej/activej/files/6707990/logs_and_dump.zip)

Hm, it really seams to be a problem with tcp implementation itself. Thanks for links!

**Comment by eduard-vasinskyi** [comment] 2022-02-17 08:36
I will close the issue for now, since I could not reproduce it on my side. 
If anyone has the same problem with a file upload, please reopen this issue.

**Closed by eduard-vasinskyi** 2022-02-17 08:36 UTC
